[theme]
base="light"
primaryColor="#1E88E5"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F5F5F5"
textColor="#31333F"
font="sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
serverAddress = "localhost"
serverPort = 8501

[runner]
fixMatplotlib = true
